### ISSUE TITLE
Recent installability jobs fail on prepare

### ISSUE THREAD

**Issue by psss** [fedora-ci/installability-pipeline#21]
I've ran into several recent installability jobs which fail during the [prepare](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/installability-pipeline/job/master/38957/testReport/%28root%29/tests/_prepare/) test with the following failure:

    Create repo file: /etc/yum.repos.d/brew-76120342.repo
    /usr/local/bin/mtps-get-task: line 212: $1: unbound variable

@msrb, could you please have a look into this? Thanks.

**Comment by jimbair** [comment]
For cross reference: https://pagure.io/fedora-ci/general/issue/285

**Comment by msrb** [comment]
This is caused by Testing Farm regression: https://pagure.io/fedora-ci/general/issue/284.
